version: '3'
services:
  db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - ../labs:/etc/labs/sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
